arkeonetwork/arkeo

sentinel/auth.go
sentinel/auth_test.go
sentinel/event_stream.go
sentinel/memstore.go

1) sentinel now filters contract/claims based on its own pubkey. should reduce resource demands
2) contracts auto get deleted from memory when they expire so we don't have a "memory leak"
3) Thrashing sentinel with authenticated but bogus requests get rate limited as well
4) switched authenticated from multiple query args to a single query arg (`arkauth`). Headers don't allow enough space to be used, therefore, query arg is our best option. The special formatted string does need to be url encoded (since it uses `:`, in the string)

improvements to sentinel

---

x/arkeo/keeper/msg_server_open_contract.go

fixes `'failed to execute message; message index: 0: pay-as-you-go 20 (client) vs
20 (provider): mismatch contract rate'`

fix: pay-as-you-go client/provider rate validation

---

common/chain.go
common/chain_test.go
sentinel/event_stream.go
sentinel/memstore.go
sentinel/sentinel.go

adds a new API endpoint to allow providers to pull unclaim rewards list from their own node. These can then be broadcast to the chain via `arkeod tx arkeo claim-contract-income` command

add open claims endpoint

---

.trunk/trunk.yaml
app/app.go
proto/arkeo/claim/claim_record.proto
proto/arkeo/claim/genesis.proto
proto/arkeo/claim/params.proto
testutil/keeper/arkeo.go
testutil/keeper/claim.go
testutil/utils/utils.go
x/claim/docs/01_concepts.md
x/claim/docs/02_state.md
x/claim/docs/03_events.md
x/claim/docs/04_hooks.md
x/claim/docs/05_params.md
x/claim/docs/README.md
x/claim/genesis.go
x/claim/genesis_test.go
x/claim/keeper/claim.go
x/claim/keeper/claim_test.go
x/claim/keeper/keeper.go
x/claim/keeper/msg_server_claim_eth.go
x/claim/keeper/msg_server_claim_eth_test.go
x/claim/keeper/msg_server_test.go
x/claim/keeper/params.go
x/claim/keeper/params_test.go
x/claim/keeper/query_claim_record_test.go
x/claim/types/events.go
x/claim/types/expected_keepers.go
x/claim/types/params.go

PR is somewhat untested with waiting to determine the best way to get integration tests built out but it should not affect any arkeo module functionality and continues to build out needed functionality in the claim module.
Summary of changes:
1. Adds keeper dependencies to claimKeeper for the bankKeeper and AccountKeeper to help with transferring tokens during claiming process
2. Modifies claim records to include a single coin vs coins for rewards and all associated functionality.  
3. Adds a new param for the module to determine the amount of dust all airdrop users should get prior to claiming
4. Moves `MakeTestCodec` into a util file so it can be shared across modules and avoid circular imports
5. fixes genesis export for claim module and needed params storage mechanism 
6. Adds …

Claim arkeo when claiming from ETH

---

sentinel/auth.go
x/arkeo/keeper/keeper.go
x/claim/client/cli/tx.go
x/claim/module_simulation.go

RemoteAddr is not always given you the correct IP address , if the end user is sitting behind a NAT/Proxy , then it will only see the proxy's IP address.
Also , if sentinel is deployed behind a load balancer , then it will only see the load balancer's ip.
We check `X-Real-Ip` , `X-Forward-For` , and if these two are both empty , then use `RemoteAddr` from http

Fix RemoteAddr

---

app/app.go
x/claim/keeper/hooks.go
x/claim/keeper/keeper.go

merge #45 and #46 first, rebase, and change to merge into master
This PR adds the needed event hooks into the claim module to respond to events from the staking and govt modules that will trigger claims for arkeo airdrops
needs additional integration tests and will add them to the list in #42

adds event hooks for arkeo claims

---

docker-compose.yml

I usually run `docker compose up --build -d` locally , this will start up `arkeod` genesis node , and also a validator node in the network .
Recent change in docker-compose.yml break it , so add this back to get it fixed

Fix local mocknet

---

docs/static/openapi.yml
go.mod
go.sum
proto/arkeo/arkeo/keeper.proto
proto/arkeo/arkeo/tx.proto
proto/arkeo/claim/claim_record.proto
proto/arkeo/claim/genesis.proto
proto/arkeo/claim/params.proto
proto/arkeo/claim/query.proto
proto/arkeo/claim/tx.proto
ts-client/arkeonetwork.arkeo.claim/module.ts
ts-client/arkeonetwork.arkeo.claim/registry.ts
ts-client/arkeonetwork.arkeo.claim/rest.ts
ts-client/arkeonetwork.arkeo.claim/types/arkeo/claim/claim_record.ts
ts-client/arkeonetwork.arkeo.claim/types/arkeo/claim/tx.ts
x/claim/client/cli/tx.go
x/claim/client/cli/tx_add_claim.go
x/claim/client/cli/tx_add_claim_testnet.go
x/claim/keeper/msg_server_add_claim.go
x/claim/keeper/msg_server_add_claim_testnet.go
x/claim/keeper/msg_server_add_claim_testnet_test.go
x/claim/module_simulation.go
x/claim/simulation/add_claim.go
x/claim/types/claim_record.go
x/claim/types/codec.go
x/claim/types/message_add_claim.go
x/claim/types/message_add_claim_test.go

close #74 
This PR add a new message `add-claim` , which will only available when the binary is build with `--tags testnet`  , so we could broadcast a `MsgAddClaim` message to create a claim record in key value store for test purpose.
This feature will be removed before mainnet launch
There are some format changes on proto files , because I run `make proto-format` command

Add "add-claim" feature for testnet

---

app/app.go
app/app_mainnet.go
app/app_testnet.go

Fix #82  , this PR to use `tarkeo` as address prefix for testnet , and `arkeo` address prefix only for mainnet.
for chain-id , it will be set only on genesis

use tarkeo address prefix for testnet

---

sentinel/memstore.go

sentinel ignore expired contracts in memstore when getting active contract

Sentinel Ignore Expired

---

arkeocli/arkeocli.go
arkeocli/bond.go
arkeocli/bond_test.go
arkeocli/utils.go
cmd/arkeod/main.go

poc supports bond provider via flags/interactive:
```
arkeod arkeo bond-provider                                           
Specify from key or address: adam
Specify provider pubkey: tarkeopub1addwnpepq2tjwwcpqwswatymx7uw3q75sqhljmp0qw3pz2fvnavkv7k2jvknqk25q7j
Specify chain (e.g. gaia-mainnet-rpc-archive, btc-mainnet-fullnode, etc): gaia-mainnet-rpc-archive
Specify bond amount (e.g. 100uarkeo): 456uarkeo
auth_info:
fee:
amount: []
...
txhash: 3BD522DD672AD8C0E06B7C6BE20DC2ABDC849D2AB52322C98C8718E400DF4DE7
```

extended cli poc

---

arkeocli/arkeocli.go
arkeocli/bond.go
arkeocli/mod.go
arkeocli/utils.go

implements mod-provider arkeo cli
refactor to infer provider pubkey from key for bond/mod if not specified
```
arkeod arkeo mod-provider
Specify from key or address: adam
Specify service (e.g. gaia-mainnet-rpc-archive, btc-mainnet-fullnode, etc): gaia-mainnet-rpc-archive
Specify status (one of online or offline): online
Specify public endpoint where metadata can be found: http://x.y.z
Increment nonce to signal provider metadata changed: 1
Specify minimum contract duration (in blocks): 10
Specify maximum contract duration (in blocks): 100
Specify settlement duration (in blocks): 10
Specify rate for subscription contracts: 5
Specify rate for pay-as-you-go contracts: 10
auth_info:
fee:
amount: []
gas_limit: "200000"
granter: ""
payer: ""
signer_infos: []
tip: null
body:
extension_options: [] …
```

mod-provider

---

.github/workflows/release.yml

* updates the dev-drprasad/delete-tag-and-release version from 0.2.0->0.2.1

fix ci might_release job

---

proto/arkeo/arkeo/tx.proto
sentinel/auth.go
sentinel/auth_test.go
test/regression/cmd/operations.go
test/regression/cmd/run.go
test/regression/suites/contracts/pay-as-you-go.yaml
tools/curleo/main.go
x/arkeo/client/cli/tx_claim_contract_income.go
x/arkeo/keeper/msg_server_claim_contract_income.go
x/arkeo/keeper/msg_server_claim_contract_income_test.go
x/arkeo/keeper/msg_server_open_contract_test.go
x/arkeo/types/message_claim_contract_income.go
x/arkeo/types/message_claim_contract_income_test.go

The spender pubkey is a "vestigial tail" of sorts and is not needed.

Remove spender from claims

---

test/regression/mnt/exports/suites_contracts_pay-as-you-go.json
test/regression/mnt/exports/suites_contracts_subscription.json
x/arkeo/configs/config_v1.go
x/arkeo/keeper/manager_test.go

tweaking the emission curve from a 4 --> 6, which reduces the rate of block emissions. Yield for validators/delegates will be less but the reserve will last longer. From memory, a value of 6 creates a similar emission schedule as Bitcoin (but continuous instead halving every 4 years)

tweak emission curve

---

docker-compose.yml
infra/k8s/sentinel-config.yaml
sentinel/conf/configuration.go
sentinel/conf/configuration_test.go
sentinel/event_stream_test.go
sentinel/sentinel.go
test/regression/cmd/run.go

this manual hack for supporting gaia archive node was put in for phase 1 testing and should be removed at this point for phase 2. Need to make sure people are testing the infra of arkeo rather than some other system remotely (although there is a way to proxy requests to another server externally)

remove gaia archive override

---

docker-compose.yml
sentinel/auth.go
sentinel/conf/configuration.go
sentinel/conf/configuration_test.go
sentinel/contract_store.go
sentinel/memstore.go
sentinel/routes.go
sentinel/sentinel.go
test/regression/cmd/operations.go
test/regression/cmd/run.go
test/regression/cmd/template.go
test/regression/mnt/exports/suites_sentinel_contract_config.json
test/regression/suites/sentinel/contract_config.yaml
test/regression/templates/contract.yaml

This adds the ability for a contract owner to configure a contract to have restrictions. Each time they read/write (GET/POST) a contract configuration, its has to be signed in the `contractauth` query arg, using this string format
```
<contract id>:<timestamp>
```
timestamp is the current epoch. Can be in seconds, milliseconds, etc
Contract owners can set the following
* per user rate limit
* whitelisted IP list
* CORs (allowed origins, methods or headers)
These configurations can be done by hitting sentinel at the following uri
```
http://<ip address>:3636/manage/contract/<id>?=contractauth=<id>:<timestamp>:<signature>
```

contract restrictions

---

Makefile
common/chain_test.go
common/service.go
common/service_test.go
directory/utils/utils.go
go.mod
go.sum
sentinel/sentinel.go
test/regression/cmd/operations.go
test/regression/cmd/run.go
test/regression/suites/contracts/pay-as-you-go.yaml
test/regression/suites/contracts/subscription.yaml
test/regression/suites/sentinel/contract_config.yaml
test/regression/suites/sentinel/sentinel.yaml
tools/mock-daemon/main.go

Fixes #110 
This adds the ability for sentinel to support websocket requests. Accounting/billing is being punted on to refactor another day. Current proposal is disable websockets access for free tier and pay-as-you-go requests.
This PR also removes the utilization of swapi.dev from regression tests. Instead a new mock daemon is created to run tests against. This was done because we needed something that supports websockets (star wars didn't support it), and also keeps integration tests local (good for in-flight coding)

add websocket support for sentinel

---

sentinel/sentinel.go

kubernetes doesn't allow env vars with dashes in the name. Because of this, switching the lookup with underscores.

replace dash with underscore

---

Makefile
app/app.go
docs/static/openapi.yml
scripts/genesis.sh
scripts/validator.sh
sentinel/auth.go
test/regression/cmd/config.go
testnet/config/genesis.json
x/claim/keeper/claim.go
x/claim/keeper/msg_server_claim_eth.go
x/claim/keeper/query_claim_record_test.go

- Fix Eth signature verification
- Fix Claim module not being added to maccPerms
- Fix openApi for claim record query
- Fix error when no claimrecord is shown defaulting to ARKEO chain
- Update genesis.json to be `claimarkeo` instead of `claim`
- Add claimrecords when running testnet/localnet
- typos
- enable CORs for localnet/testnet
- lint
- update tests

Add claim records for localnet

---

.github/workflows/test.yaml
CHANGELOG.md
Makefile
directory/indexer/consumer.go
directory/indexer/consumer_test.go
docs/TESTNET.md
sentinel/event_stream.go
test/regression/cmd/export.go
test/regression/suites/contracts/pay-as-you-go.yaml
test/regression/suites/contracts/subscription.yaml
x/arkeo/keeper/events.go

- Fixed regression testing 
- Fixed Consumers in directory service 
- Docs update

fix: regression testing and doc update

---

docs/TESTNET.md
docs/VALIDATOR.md

Moved wallet creation after setting keyring client to "test", because default is "os" in TESTNET.md
Latest arkeod version requieres a .json file for sending create validator payload to the blockchain. Updated VALIDATOR.md with necessary changes.

Update testnet-3 documentation
