- Dockerfile
- Makefile
- scripts/genesis.sh
- scripts/run-arkeo.sh
Creates a dockerfile to build arkeo docker image
> add dockerfile

- .github/workflows/docker-build-push.yml
- Dockerfile
- docker-compose.yml
- scripts/genesis.sh
- scripts/sentinel.sh
- x/arkeo/types/query.pb.gw.go
This adds a docker compose file making it possible to build a full stack mocknet environment
> add docker compose file

- sentinel/auth.go
- sentinel/memstore.go
- sentinel/memstore_test.go
- tools/curleo/main.go
- x/arkeo/types/keeper.go
found and squashed bugs in full stack testing
> various patches

- sentinel/auth.go
- sentinel/auth_test.go
- sentinel/event_stream.go
- sentinel/memstore.go
- sentinel/memstore_test.go
- sentinel/sentinel.go
- x/arkeo/types/query.pb.gw.go
> Setup logging in sentinel , remove usage of fmt.Println

- docs/static/openapi.yml
- proto/arkeo/claim/claim_record.proto
- ts-client/arkeonetwork.arkeo.claim/rest.ts
- ts-client/arkeonetwork.arkeo.claim/types/arkeo/claim/claim_record.ts
- x/claim/docs/01_concepts.md
- x/claim/docs/03_events.md
- x/claim/docs/README.md
- x/claim/keeper/claim.go
- x/claim/keeper/claim_test.go
- x/claim/types/address.go
- x/claim/types/events.go
- x/claim/types/keys.go
removes thorchain from the claim module as we do not have the ability to easily have users sign a message.
> removes thorchain from claim specification

- readme.md
Outline how to set up a node on the Arkeo network. The boilerplate readme and the node instruction are now merged.
Note that a couple of things are missing:
binary version to be installed
location of the genesis file
seeds
binary name
> Node installaton guide

- x/arkeo/keeper/msg_server_open_contract.go
adds a bit clearer error messaging
> more descriptive errors

- Dockerfile
- sentinel/conf/configuration_test.go
- tools/curleo/main.go
- x/claim/types/keys.go
> Fix curleo can't find key when using keyring-backend=os

- sentinel/auth.go
- sentinel/auth_test.go
> Fall back to free tier when paid tier failed

- x/arkeo/keeper/contracts.go
- x/arkeo/keeper/keeper.go
- x/arkeo/keeper/manager.go
- x/arkeo/keeper/manager_test.go
- x/arkeo/keeper/msg_server_bond_provider.go
- x/arkeo/keeper/msg_server_close_contract.go
- x/arkeo/keeper/msg_server_close_contract_test.go
- x/arkeo/keeper/msg_server_open_contract.go
- x/arkeo/keeper/msg_server_open_contract_test.go
- x/arkeo/types/errors.go
- x/arkeo/types/keeper.go
> adds removal of non active contracts from user

- proto/arkeo/arkeo/genesis.proto
- x/arkeo/genesis.go
- x/arkeo/genesis_test.go
- x/arkeo/keeper/contracts.go
- x/arkeo/keeper/keeper.go
> Fix genesis export and import 

- Dockerfile
- docker-compose.yml
- infra/k8s/arkeod-sts.yaml
- infra/k8s/sentinel-sts.yaml
infra: arkeod default arkeo home, stateful sets use testnet image
> testnet launch

- arkeocli/arkeocli.go
- arkeocli/claim.go
- arkeocli/close.go
- arkeocli/utils.go
```
arkeod arkeo close-contract
Specify from key or address: adam
Specify provider pubkey: tarkeopub1addwnpepq0h7hn9jzhkfwkxgp6kl3ljtjxfvz48emzdrrt5epzjrumpx9kz3w9mjsq9
Specify client pubkey: tarkeopub1addwnpepq2tjwwcpqwswatymx7uw3q75sqhljmp0qw3pz2fvnavkv7k2jvknqk25q7j
Specify service (e.g. gaia-mainnet-rpc-archive, btc-mainnet-fullnode, etc): gaia-mainnet-rpc-archive
auth_info:
fee:
amount: []
gas_limit: "200000"
granter: ""
payer: ""
signer_infos: []
tip: null
body:
extension_options: []
memo: ""
messages:
- '@type': /arkeo.arkeo.MsgCloseContract
contract_id: "27"
creator: tarkeo14q4qnm4tmkm9xuhjwu0vw0f8xy7ztexek44nw3
non_critical_extension_options: []
timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 0
codespace: ""
data: ""
events: …
```
> Close Contract CLI

- x/arkeo/keeper/manager.go
> refactor math

- x/arkeo/keeper/manager.go
- x/arkeo/keeper/manager_test.go
refactors the block rewards from the reserve to include non-arkeo tokens
> refactor validator/delegate payouts to include non-arkeo tokens

- common/service.go
- common/service_test.go
> adds moar services

- common/common.go
- sentinel/sentinel.go
Seems like sentinel routing was broken in a previous change, which broke the `infra` repo from being functional. Making some changes to fix this. Will be some things to fix, but will find them as I do more testing and will open up a follow on PR.
> refactor sentinel routing to work again

- sentinel/auth.go
- sentinel/auth_test.go
- x/arkeo/keeper/msg_server_claim_contract_income.go
> Strict contract auth

- sentinel/auth.go
- test/regression/mnt/exports/suites_contracts_pay-as-you-go.json
- test/regression/suites/contracts/pay-as-you-go.yaml
- x/arkeo/keeper/contracts.go
- x/arkeo/keeper/contracts_test.go
- x/arkeo/keeper/manager.go
- x/arkeo/keeper/msg_server_claim_contract_income.go
- x/arkeo/keeper/msg_server_close_contract.go
- x/arkeo/keeper/msg_server_close_contract_test.go
- x/arkeo/keeper/msg_server_open_contract.go
- x/arkeo/types/keeper.go
> users can now cancel pay as you go contracts

- sentinel/sentinel.go
- sentinel/sentinel_test.go
- test/regression/suites/contracts/pay-as-you-go.yaml
> proxy active-contract requests

- scripts/claim-rewards.bash
> add script to claim rewards

- directory/db/contract.go
- directory/indexer/contract.go
- sentinel/auth.go
- sentinel/event_stream.go
- sentinel/sentinel.go
- test/regression/cmd/operations.go
- test/regression/mnt/exports/suites_contracts_pay-as-you-go.json
- test/regression/mnt/exports/suites_contracts_subscription.json
- test/regression/mnt/exports/suites_core_send.json
- test/regression/mnt/exports/suites_initialize.json
- test/regression/mnt/exports/suites_providers_providers.json
- test/regression/mnt/exports/suites_sentinel_contract_config.json
- test/regression/mnt/exports/suites_sentinel_sentinel.json
- test/regression/suites/contracts/pay-as-you-go.yaml
- test/regression/suites/contracts/subscription.yaml
- x/arkeo/client/cli/tx_open_contract.go
- x/arkeo/keeper/contracts.go
- x/arkeo/keeper/msg_server_close_contract_test.go
- x/arkeo/keeper/msg_server_open_contract_test.go
- x/arkeo/types/keeper.go
adds the ability to auth with sentinel using headers instead of uri paths and query args
> Header auth

- x/arkeo/keeper/msg_server_claim_contract_income.go
> fix handler check

- common/service.go
Extend services to list blockbooks
> Add Blockbooks

- CHANGELOG.md
- Dockerfile.localnet
- Makefile
- docker-compose-localnet.yaml
- scripts/genesis.sh
- Expose chain's rpc endpoint from the docker 
- update genesis to update rpc address
> fix: localnet docker

- CHANGELOG.md
- app/app.go
- app/export.go
- config.yml
- directory/indexer/consumer.go
- scripts/genesis.sh
- test/regression/mnt/exports/suites_contracts_pay-as-you-go.json
- test/regression/mnt/exports/suites_contracts_subscription.json
- test/regression/mnt/exports/suites_core_send.json
- test/regression/mnt/exports/suites_initialize.json
- test/regression/mnt/exports/suites_providers_providers.json
- test/regression/mnt/exports/suites_sentinel_contract_config.json
- test/regression/mnt/exports/suites_sentinel_sentinel.json
- test/regression/suites/contracts/pay-as-you-go.yaml
- test/regression/suites/contracts/subscription.yaml
- x/arkeo/module.go
- x/claim/module.go
Fixed bug renaming address
Added Timeout
> fix: claim timeout

- .goreleaser-cross.yaml
- .goreleaser.yaml
- CHANGELOG.md
- test/regression/cmd/export.go
- test/regression/mnt/exports/suites_contracts_pay-as-you-go.json
- test/regression/mnt/exports/suites_contracts_subscription.json
- test/regression/mnt/exports/suites_core_send.json
- test/regression/mnt/exports/suites_initialize.json
- test/regression/mnt/exports/suites_providers_providers.json
- test/regression/mnt/exports/suites_sentinel_contract_config.json
- test/regression/mnt/exports/suites_sentinel_sentinel.json
- x/claim/keeper/msg_server_claim_thorchain.go
- x/claim/keeper/msg_server_claim_thorchain_test.go
allow mainnet Thorchain claim server address to claim
> fix: thor mainnet error

- .github/workflows/release.yml
Reverts arkeonetwork/arkeo#305
> Revert "chore: update ci go releaser"

- CHANGELOG.md
- tools/converter.go
- x/claim/keeper/msg_server_claim_thorchain.go
- x/claim/types/types.go
Updated event labels on thorchain delegate events
> fix: tc delegate event labels

- CHANGELOG.md
- scripts/genesis.sh
Instead of giving people a claimable amount of arkeo, we will be setting fees to zero
> chore: set minimum gas price to zero so people can claim
